PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE Film(idFilm INTEGER PRIMARY KEY AUTOINCREMENT, titre TEXT);
INSERT INTO Film VALUES(1,'Les évadés');
INSERT INTO Film VALUES(2,'Le parrain');
INSERT INTO Film VALUES(3,'La vie de Pi');
INSERT INTO Film VALUES(4,'Chocolat');
INSERT INTO Film VALUES(5,'Scarface');
INSERT INTO Film VALUES(6,'Rango');
CREATE TABLE Acteur(idActeur INTEGER PRIMARY KEY AUTOINCREMENT, nom TEXT, prenom TEXT);
INSERT INTO Acteur VALUES(1,'Deep','Johnny');
INSERT INTO Acteur VALUES(2,'Pacino','Al');
INSERT INTO Acteur VALUES(3,'Sharma','Suraj');
CREATE TABLE Filmographie(idActeur TEXT, idFilm TEXT, foreign key (idActeur) references Acteur(idActeur), foreign key (idFilm) references Film(idFilm), primary key (idActeur, idFilm));
INSERT INTO Filmographie VALUES('1','4');
INSERT INTO Filmographie VALUES('1','6');
INSERT INTO Filmographie VALUES('2','2');
INSERT INTO Filmographie VALUES('2','5');
INSERT INTO Filmographie VALUES('3','3');
INSERT INTO sqlite_sequence VALUES('Acteur',3);
INSERT INTO sqlite_sequence VALUES('Film',6);
COMMIT;
